title: HarmonyHub504
description: HarmonyHub504 is a music recommendation and management platform built with Flask, SQLAlchemy, and Spotipy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
